language: ruby
rvm:
  - 2.1.6

notifications:
  email:
    - travis@brugger.eu

bundler_args: --without development

addons:
  code_climate:
    repo_token: c60efb15bb71c8e74eceaa3c1f4d6c9db6b6a192f86c04cd213796f52e29dfd3
